name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    
    - name: Checkout embassy repo
      uses: actions/checkout@v3
      with:
       repository: embassy-rs/embassy
       path: embassy
    
    - name: ls
      run: ls -al
      
    - name: cd repo
      run: cd embassy-test-1
    
    - name: ls2
      run: ls -al
      
    - name: Build
      run: cargo build --verbose

